#!/usr/bin/env python
"""
Taxonomic-sampling summary for a merged.tsv generated by the chrombase pipeline.

This version preserves your phylum_to_taxid dict at top (so you can keep it),
and adds code to:
 - parse taxids from the 'Organism Taxonomic ID' column
 - use ete4.NCBITaxa to get lineage & ranks
 - record observed phyla, classes, and orders
 - print "found x out of y" summaries (NCBI and GBIF)
 - write observed_* TSV outputs
"""

import re
import csv
from collections import defaultdict

import pandas
import requests

# not sure if these are accurate, so uses ete4 to update them
# 32 animal phyla and their taxids
# I checked all of these. Sipuncula are not considered a phylum anymore
phylum_to_taxid = {
                   "Nematoda": 6231,
                   "Nematomorpha": 33310,
                   "Priapulida": 33467,
                   "Kinorhyncha": 51516,
                   "Loricifera": 310840,
                   "Onychophora": 27563,
                   "Arthropoda": 6656,
                   "Tardigrada": 42241,
                   "Sipuncula": 6433,
                   "Mollusca": 6447,
                   "Annelida": 6340,
                   "Bryozoa": 10205,
                   "Phoronida": 120557,
                   "Nemertea": 6217,
                   "Platyhelminthes": 6157,
                   "Rotifera": 10190,
                   "Brachiopoda": 7568,
                   "Entoprocta": 43120,
                   "Gastrotricha": 33313,
                   "Xenacoelomorpha": 1312402,
                   "Echinodermata": 7586,
                   "Hemichordata": 10219,
                   "Chordata": 7711,
                   "Cycliophora": 69815,
                   "Gnathostomulida": 66780,
                   "Chaetognatha": 10229,
                   "Orthonectida": 33209,
                   "Cnidaria": 6073,
                   "Placozoa": 10226,
                   "Ctenophora": 10197,
                   "Porifera": 6040
                   }


def parse_taxid(x):
    """Return int taxid or None. Accept '12345', 'taxid:12345', floats from pandas, etc."""
    if pandas.isna(x):
        return None
    s = str(x).strip()
    m = re.search(r'(\d+)', s)
    if not m:
        return None
    try:
        return int(m.group(1))
    except Exception:
        return None


def gbif_count(rank, higher_key=1):
    """Return integer count from GBIF species search (accepted only)."""
    BASE = "https://api.gbif.org/v1/species/search"
    params = {"rank": rank, "highertaxon_key": higher_key, "status": "ACCEPTED", "limit": 0}
    r = requests.get(BASE, params=params, timeout=30)
    r.raise_for_status()
    return int(r.json().get("count", 0))


def gbif_species_count(higher_key=1):
    """Return integer count of accepted species from GBIF."""
    BASE = "https://api.gbif.org/v1/species/search"
    params = {"rank": "SPECIES", "highertaxon_key": higher_key, "status": "ACCEPTED", "limit": 0}
    r = requests.get(BASE, params=params, timeout=30)
    r.raise_for_status()
    return int(r.json().get("count", 0))


def get_gbif_key_for_taxon(scientific_name):
    """Get GBIF usage key for a scientific name."""
    # Known GBIF backbone taxonomy keys for animal phyla (verified from GBIF match API)
    known_keys = {
        "Ctenophora": 51,
        "Onychophora": 62,
        "Porifera": 105,
        "Placozoa": 76,
        "Cnidaria": 43,
        "Xenacoelomorpha": 7190138,
        "Chaetognatha": 55,
        "Hemichordata": 75,
        "Echinodermata": 50,
        "Chordata": 44,
        "Nematoda": 5967481,
        "Nematomorpha": 64,
        "Priapulida": 5963150,
        "Kinorhyncha": 5959089,
        "Loricifera": 5967457,
        "Tardigrada": 14,
        "Arthropoda": 54,
        "Mollusca": 52,
        "Annelida": 42,
        "Platyhelminthes": 108,
        "Rotifera": 91,
        "Bryozoa": 53,
        "Brachiopoda": 110,
        "Entoprocta": 8173593,
        "Nemertea": 63,
        "Phoronida": 19,
        "Gastrotricha": 22,
        "Gnathostomulida": 77,
        "Orthonectida": 5967456,
        "Cycliophora": 45,
        "Sipuncula": 74
    }
    
    # Check known keys first
    if scientific_name in known_keys:
        return known_keys[scientific_name]
    
    # Try the match API
    BASE = "https://api.gbif.org/v1/species/match"
    params = {"name": scientific_name, "rank": "PHYLUM"}
    try:
        r = requests.get(BASE, params=params, timeout=30)
        r.raise_for_status()
        data = r.json()
        # Only accept if we have a good match
        if data.get("matchType") in ["EXACT", "HIGHERRANK"] and data.get("usageKey"):
            return data.get("usageKey")
    except Exception:
        pass
    
    # Try search API as fallback
    try:
        BASE = "https://api.gbif.org/v1/species/search"
        params = {"q": scientific_name, "rank": "PHYLUM", "limit": 1}
        r = requests.get(BASE, params=params, timeout=30)
        r.raise_for_status()
        data = r.json()
        results = data.get("results", [])
        if results and results[0].get("scientificName", "").upper() == scientific_name.upper():
            return results[0].get("key")
    except Exception:
        pass
    
    return None


def extract_phylum_class_order(ncbi, tid, metazoa_tid):
    """
    Return (phylum_tid, phylum_name, class_tid, class_name, order_tid, order_name)
    or (None, None, None, None, None, None) if not resolvable or not under Metazoa.
    """
    try:
        lineage = ncbi.get_lineage(tid)
    except Exception:
        return (None,)*6
    if not lineage:
        return (None,)*6

    ranks_map = ncbi.get_rank(lineage)
    names_map = ncbi.get_taxid_translator(lineage)

    # ensure tid/lineage is under Metazoa (or equal)
    if metazoa_tid not in lineage and tid != metazoa_tid:
        return (None,)*6

    # search lineage for phylum/class/order; prefer the ancestor (higher in tree)
    ph_tid = cl_tid = ord_tid = None
    # iterate from root -> tip by reversing lineage if needed; this heuristic covers typical return order
    for anc in reversed(lineage):  # ensure we see higher-level ancestors first
        r = ranks_map.get(anc)
        if r == 'phylum' and ph_tid is None:
            ph_tid = anc
        if r == 'class' and cl_tid is None:
            cl_tid = anc
        if r == 'order' and ord_tid is None:
            ord_tid = anc
    ph_name = names_map.get(ph_tid) if ph_tid else None
    cl_name = names_map.get(cl_tid) if cl_tid else None
    ord_name = names_map.get(ord_tid) if ord_tid else None
    return ph_tid, ph_name, cl_tid, cl_name, ord_tid, ord_name


def count_ncbi_rank(ncbi, metazoa_tid, rank):
    """Count nodes of exact rank under Metazoa in the local NCBI DB."""
    cand = ncbi.get_descendant_taxa(metazoa_tid, rank_limit=rank)
    ranks_map = ncbi.get_rank(cand)
    kept = [t for t in cand if ranks_map.get(t) == rank]
    return len(kept)


def main():
    from ete4 import NCBITaxa  # explicit import per your request

    # path to the merged.tsv you mentioned (leave as-is)
    TAXID_COL = "Organism Taxonomic ID"

    # read table (safely read as strings)
    df = pandas.read_csv(dfpath, sep='\t', dtype=str)
    if TAXID_COL not in df.columns:
        raise KeyError(f"Column '{TAXID_COL}' not found in {dfpath}. Columns: {df.columns.tolist()}")

    # parse taxids (deduplicate)
    df['parsed_taxid'] = df[TAXID_COL].map(parse_taxid)
    taxids = sorted({tid for tid in df['parsed_taxid'].unique() if tid is not None})
    print(f"Parsed {len(taxids)} unique taxids from file (nulls ignored).")

    # initialize NCBI taxonomy (may download/build on first run)
    ncbi = NCBITaxa()
    try:
        metazoa_tid = ncbi.get_name_translator(['Metazoa']).get('Metazoa', [33208])[0]
    except Exception:
        metazoa_tid = 33208
    print("Metazoa taxid used:", metazoa_tid)

    observed_phyla = {}
    observed_classes = {}
    observed_orders = {}
    unresolved = []

    # iterate taxids and record phylum/class/order
    for tid in taxids:
        ph_tid, ph_name, cl_tid, cl_name, ord_tid, ord_name = extract_phylum_class_order(ncbi, tid, metazoa_tid)
        if ph_tid:
            observed_phyla[ph_tid] = ph_name
        if cl_tid:
            observed_classes[cl_tid] = cl_name
        if ord_tid:
            observed_orders[ord_tid] = ord_name
        if not (ph_tid or cl_tid or ord_tid):
            unresolved.append(tid)

    print(f"Observed phyla (unique): {len(observed_phyla)}")
    print(f"Observed classes (unique): {len(observed_classes)}")
    print(f"Observed orders (unique): {len(observed_orders)}")
    if unresolved:
        print(f"Could not resolve phylum/class/order for {len(unresolved)} taxids (examples): {unresolved[:8]}")

    # NCBI totals (y_ncbi)
    ncbi_phyla = count_ncbi_rank(ncbi, metazoa_tid, 'phylum')
    ncbi_classes = count_ncbi_rank(ncbi, metazoa_tid, 'class')
    ncbi_orders = count_ncbi_rank(ncbi, metazoa_tid, 'order')

    # GBIF totals (y_gbif)
    try:
        gbif_phyla = gbif_count('PHYLUM')
        gbif_classes = gbif_count('CLASS')
        gbif_orders = gbif_count('ORDER')
    except Exception as e:
        print("GBIF query failed:", e)
        gbif_phyla = gbif_classes = gbif_orders = None

    # Also show how your hard-coded dict compares (y_dict)
    dict_phyla = len(phylum_to_taxid)

    # Print summary
    print("\nSUMMARY:")
    print(f"Phyla: observed {len(observed_phyla)}  |  dict has {dict_phyla}  |  NCBI has {ncbi_phyla}", end='')
    if gbif_phyla is not None:
        print(f"  |  GBIF backbone has {gbif_phyla}")
    else:
        print()
    print(f"Classes: observed {len(observed_classes)}  |  NCBI has {ncbi_classes}", end='')
    if gbif_classes is not None:
        print(f"  |  GBIF backbone has {gbif_classes}")
    else:
        print()
    print(f"Orders: observed {len(observed_orders)}  |  NCBI has {ncbi_orders}", end='')
    if gbif_orders is not None:
        print(f"  |  GBIF backbone has {gbif_orders}")
    else:
        print()

    # write TSV outputs
    with open('observed_phyla.tsv', 'w', newline='') as fh:
        w = csv.writer(fh, delimiter='\t')
        w.writerow(['phylum_taxid', 'phylum_name'])
        for tid, name in sorted(observed_phyla.items(), key=lambda x: (x[1] or '', x[0])):
            w.writerow([tid, name])

    with open('observed_classes.tsv', 'w', newline='') as fh:
        w = csv.writer(fh, delimiter='\t')
        w.writerow(['class_taxid', 'class_name'])
        for tid, name in sorted(observed_classes.items(), key=lambda x: (x[1] or '', x[0])):
            w.writerow([tid, name])

    with open('observed_orders.tsv', 'w', newline='') as fh:
        w = csv.writer(fh, delimiter='\t')
        w.writerow(['order_taxid', 'order_name'])
        for tid, name in sorted(observed_orders.items(), key=lambda x: (x[1] or '', x[0])):
            w.writerow([tid, name])

    print("Wrote observed_phyla.tsv, observed_classes.tsv, observed_orders.tsv")

    # Get GBIF species counts for each phylum
    print("\nQuerying GBIF for species counts per phylum...")
    phylum_species_counts = {}
    
    # Get total accepted animal species from GBIF
    try:
        # Metazoa key in GBIF is 1
        total_animal_species = gbif_species_count(higher_key=1)
        print(f"Total accepted animal species in GBIF: {total_animal_species:,}")
    except Exception as e:
        print(f"Failed to get total animal species count: {e}")
        total_animal_species = None
    
    # Get species counts for each phylum in phylum_to_taxid
    for phylum_name, taxid in sorted(phylum_to_taxid.items()):
        try:
            # Get GBIF key for this phylum
            gbif_key = get_gbif_key_for_taxon(phylum_name)
            if gbif_key:
                species_count = gbif_species_count(higher_key=gbif_key)
                phylum_species_counts[phylum_name] = species_count
                print(f"  {phylum_name}: {species_count:,} accepted species")
            else:
                phylum_species_counts[phylum_name] = None
                print(f"  {phylum_name}: Could not find GBIF key")
        except Exception as e:
            phylum_species_counts[phylum_name] = None
            print(f"  {phylum_name}: Error - {e}")
    
    # Write GBIF species counts to text file
    with open('gbif_species_counts.txt', 'w') as fh:
        fh.write("GBIF Accepted Species Counts\n")
        fh.write("="*60 + "\n\n")
        
        if total_animal_species is not None:
            fh.write(f"Total Accepted Animal Species (Metazoa): {total_animal_species:,}\n\n")
        else:
            fh.write("Total Accepted Animal Species (Metazoa): N/A\n\n")
        
        fh.write("Accepted Species per Phylum:\n")
        fh.write("-"*60 + "\n")
        for phylum_name in sorted(phylum_to_taxid.keys()):
            count = phylum_species_counts.get(phylum_name)
            if count is not None:
                fh.write(f"{phylum_name:30s} {count:>10,}\n")
            else:
                fh.write(f"{phylum_name:30s} {'N/A':>10s}\n")
    
    print("\nWrote gbif_species_counts.txt")


if __name__ == '__main__':
    main()
